/**
 * Skill Prompt: triage
 *
 * Issue 分类，通过状态机驱动的分类角色管理 Issue。
 * 来源：auto-dev-framework/.agent/skills/triage/SKILL.md
 *
 * 适用于 Elon（CEO Agent）：Issue 分类、优先级管理
 */

export const TRIAGE_SKILL_PROMPT = [
  '## Skill: triage — Issue 分类',
  '',
  '你正在执行 triage Skill。你的任务是通过状态机驱动的分类角色管理 Issue 的生命周期。',
  '',
  '### 核心原则',
  '',
  '1. **状态驱动**：Issue 通过状态机流转',
  '2. **分类明确**：每个 Issue 有一个分类角色和一个状态角色',
  '3. **可追溯**：所有操作记录在 Issue 中',
  '4. **幂等性**：重复操作不会产生副作用',
  '',
  '### 角色定义',
  '',
  '#### 分类角色',
  '- `bug` — 某些东西坏了',
  '- `enhancement` — 新功能或改进',
  '',
  '#### 状态角色',
  '- `needs-triage` — 维护者需要评估',
  '- `needs-info` — 等待报告者提供更多信息',
  '- `ready-for-agent` — 完全指定，可由 Agent 领取',
  '- `ready-for-human` — 需要人工实现',
  '- `wontfix` — 不会处理',
  '',
  '### 状态流转',
  '',
  '```',
  '未标记 → needs-triage → needs-info → needs-triage（回复后）',
  '                     ↘ ready-for-agent',
  '                     ↘ ready-for-human',
  '                     ↘ wontfix',
  '```',
  '',
  '### 工作流程',
  '',
  '#### 1. 显示需要关注的内容',
  '查询 Issue Tracker，展示三个桶（最旧优先）：',
  '1. **未标记** — 从未分类',
  '2. **needs-triage** — 评估中',
  '3. **needs-info 且有新活动** — 需要重新评估',
  '',
  '#### 2. 分类特定 Issue',
  '1. **收集上下文** — 读取完整 Issue（body、comments、labels）',
  '2. **推荐** — 告诉维护者你的分类和状态推荐，附带理由',
  '3. **复现（仅 bug）** — 尝试复现，报告结果',
  '4. **追问（如果需要）** — 如果 Issue 需要补充，运行 grill-with-docs',
  '5. **应用结果** — 设置状态角色，添加评论',
  '',
  '#### 3. 快速状态覆盖',
  '如果维护者说"把 #42 移到 ready-for-agent"，直接执行。',
  '',
  '### 评论模板',
  '',
  '#### needs-info 模板',
  '```markdown',
  '## Triage Notes',
  '',
  '**我们已经确认的：**',
  '- 要点 1',
  '- 要点 2',
  '',
  '**我们仍然需要你 (@reporter) 提供的：**',
  '- 问题 1',
  '- 问题 2',
  '```',
  '',
  '#### Agent Brief 模板',
  '```markdown',
  '## Agent Brief',
  '',
  '**目标：** [一句话描述]',
  '',
  '**上下文：** [关键信息]',
  '',
  '**验收标准：**',
  '- [ ] 标准 1',
  '- [ ] 标准 2',
  '',
  '**约束：** [限制条件]',
  '```',
  '',
  '### 输出格式',
  '',
  '```json',
  '{',
  '  "skill": "triage",',
  '  "status": "success",',
  '  "confidence": 0.9,',
  '  "summary": "分类了 5 个 Issue：3 个 ready-for-agent，1 个 needs-info，1 个 wontfix",',
  '  "data": {',
  '    "triagedCount": 5,',
  '    "results": [',
  '      {',
  '        "issueNumber": 42,',
  '        "category": "bug",',
  '        "state": "ready-for-agent",',
  '        "reason": "问题可复现，已有明确修复方案"',
  '      }',
  '    ],',
  '    "needsAttention": {',
  '      "unlabeled": 2,',
  '      "needsTriage": 3,',
  '      "needsInfoWithActivity": 1',
  '    }',
  '  },',
  '  "next": {',
  '    "recommendedAction": "continue",',
  '    "reason": "分类完成，等待用户选择下一步"',
  '  }',
  '}',
  '```',
  '',
  '### 终止条件',
  '',
  '| 条件 | 输出 |',
  '|------|------|',
  '| 所有 Issue 分类完成 | status: success |',
  '| 需要更多信息 | status: needs_input |',
  '| 用户明确停止 | status: success |',
].join('\n')
