import type {
  AgentPermissionBoundary,
  AgentProfile,
  ApiAuthBoundary,
  ProductionObservabilityPolicy,
  RegressionGate,
  ReleaseReadinessChecklist,
  SecretRedactionPolicy,
  SecurityPolicy,
  SkillIOContract,
} from './types'

export const sprint10CreatedAt = '2026-06-16T00:00:00.000Z'

export const forbiddenExecutionActions = [
  'execute_agent',
  'execute_tool',
  'run_shell',
  'run_git',
  'write_file',
  'create_pr',
  'deploy',
  'delete',
  'call_external_api',
  'call_mcp',
  'dispatch_a2a',
  'resume_execution',
  'auto_fix',
  'bypass_permission',
]

export const forbiddenApiRouteSemantics = [
  'execute',
  'run-tool',
  'start-agent',
  'apply',
  'create-pr',
  'deploy',
  'dispatch',
  'auto-fix',
  'resume-execution',
  'bypass-permission',
  'send-external-request',
  'call-external',
  'mcp',
  'shell',
  'git',
  'write-file',
  'delete',
]

export const defaultSecurityPolicy: SecurityPolicy = {
  id: 'security-policy-sprint-10',
  policyVersion: 'sprint-10.0',
  status: 'active',
  scope: 'global',
  defaultDecision: 'deny',
  appliesTo: [
    'chat',
    'router',
    'task',
    'agent',
    'memory',
    'knowledge',
    'context',
    'a2a',
    'tool',
    'eval',
    'observability',
    'recovery',
    'collaboration',
    'file',
    'git',
    'external',
    'mcp',
    'deploy',
  ],
  allowedRecordActions: [
    'view',
    'inspect',
    'create_local_record',
    'submit_review',
    'approve_local_record',
    'reject_local_record',
    'archive_local_record',
  ],
  forbiddenExecutionActions,
  forbiddenApiRouteSemantics,
  requiresHumanConfirmationFor: [
    'high_risk_record_approval',
    'critical_risk_record_approval',
    'permission_override_request',
    'release_readiness_approval',
    'security_policy_activation',
  ],
  commandPolicyId: 'command-policy-sprint-6',
  redactionPolicyId: 'redaction-policy-sprint-8',
  secretRedactionPolicyId: 'secret-redaction-policy-sprint-10',
  apiAuthBoundaryId: 'api-auth-boundary-sprint-10',
  productionObservabilityPolicyId: 'production-observability-policy-sprint-10',
  auditRequired: true,
  correlationRequired: true,
  redactionRequired: true,
  createdBy: 'system',
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}

const commonForbiddenActions = [
  'execute_tools',
  'start_agent_runs',
  'run_shell',
  'use_git',
  'write_files',
  'create_prs',
  'deploy',
  'delete',
  'call_external_apis',
  'call_mcp',
  'dispatch_a2a',
  'bypass_kelvin',
]

export const agentProfiles: AgentProfile[] = [
  {
    id: 'kelvin',
    displayName: 'Kelvin / Chairman',
    role: 'human_owner',
    responsibility: ['final human authority', 'review high-risk local records', 'resolve ambiguity'],
    allowedActions: ['inspect', 'review', 'approve_local_record', 'reject_local_record'],
    forbiddenActions: ['bypass_policy', ...commonForbiddenActions],
    allowedOutputTypes: ['confirmation_decision', 'review_note'],
    forbiddenOutputTypes: ['execution_command'],
    skillRefs: ['human-confirmation', 'risk-review'],
    riskLevel: 'critical',
    requiresHumanConfirmation: true,
    permissionBoundaryId: 'agent-boundary-kelvin',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'claude_ceo',
    displayName: 'Claude CEO',
    role: 'ceo_agent',
    responsibility: ['plan', 'route', 'coordinate', 'decompose', 'risk assess'],
    allowedActions: [
      'propose_route_decision',
      'propose_task_decomposition',
      'propose_collaboration_plan',
      'propose_tool_call_record',
      'request_eval',
      'request_kelvin_review',
    ],
    forbiddenActions: commonForbiddenActions,
    allowedOutputTypes: ['RouteDecision', 'TaskDecomposition', 'CollaborationPlan', 'RiskAssessment', 'ToolCallProposal', 'EvalRequest'],
    forbiddenOutputTypes: ['ToolExecution', 'ShellCommand', 'FilePatch', 'GitOperation', 'DeployRun'],
    skillRefs: ['ai-builder-methodology', 'planning', 'risk-review'],
    riskLevel: 'high',
    requiresHumanConfirmation: true,
    permissionBoundaryId: 'agent-boundary-claude-ceo',
    modelIdentity: 'claude_ceo',
    systemPromptRef: 'ceo.plan-only',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'elon',
    displayName: 'Elon / CEO Persona',
    role: 'ceo_agent',
    responsibility: ['legacy CEO persona alias for existing records'],
    allowedActions: ['alias_to_claude_ceo'],
    forbiddenActions: commonForbiddenActions,
    allowedOutputTypes: ['RouteDecision', 'TaskDecomposition', 'CollaborationPlan'],
    forbiddenOutputTypes: ['ToolExecution', 'ShellCommand', 'FilePatch', 'GitOperation', 'DeployRun'],
    skillRefs: ['ai-builder-methodology'],
    riskLevel: 'high',
    requiresHumanConfirmation: true,
    permissionBoundaryId: 'agent-boundary-elon-alias',
    modelIdentity: 'claude_ceo',
    personaAlias: 'elon',
    status: 'draft',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'jobs',
    displayName: 'Jobs / Product Agent',
    role: 'product_agent',
    responsibility: ['product critique', 'user value', 'UX', 'acceptance criteria'],
    allowedActions: ['propose_product_record', 'request_review'],
    forbiddenActions: commonForbiddenActions,
    allowedOutputTypes: ['ProductReview', 'PRDRecommendation'],
    forbiddenOutputTypes: ['execution_command'],
    skillRefs: ['to-prd', 'grill-me', 'prototype'],
    riskLevel: 'medium',
    requiresHumanConfirmation: false,
    permissionBoundaryId: 'agent-boundary-jobs',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'linus',
    displayName: 'Linus / Engineering Agent',
    role: 'engineering_agent',
    responsibility: ['architecture review', 'implementation planning', 'code review recommendation'],
    allowedActions: ['propose_engineering_record', 'request_review'],
    forbiddenActions: commonForbiddenActions,
    allowedOutputTypes: ['EngineeringPlan', 'CodeReviewRecommendation'],
    forbiddenOutputTypes: ['FilePatch', 'ShellCommand', 'GitOperation'],
    skillRefs: ['tdd', 'improve-codebase-architecture'],
    riskLevel: 'high',
    requiresHumanConfirmation: true,
    permissionBoundaryId: 'agent-boundary-linus',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'turing',
    displayName: 'Turing / Verification Agent',
    role: 'verification_agent',
    responsibility: ['verification', 'checklist', 'quality gate recommendation'],
    allowedActions: ['record_eval', 'record_finding', 'recommend_gate'],
    forbiddenActions: ['auto_fix', 'mutate_target_record', ...commonForbiddenActions],
    allowedOutputTypes: ['EvalCheck', 'EvalFinding', 'QualityGateDecision'],
    forbiddenOutputTypes: ['AutoFixRun', 'ToolExecution'],
    skillRefs: ['diagnose', 'loop-review'],
    riskLevel: 'medium',
    requiresHumanConfirmation: false,
    permissionBoundaryId: 'agent-boundary-turing',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'bezos',
    displayName: 'Bezos / Customer Agent',
    role: 'customer_agent',
    responsibility: ['customer value', 'support perspective', 'business outcome critique'],
    allowedActions: ['propose_customer_record', 'request_review'],
    forbiddenActions: commonForbiddenActions,
    allowedOutputTypes: ['CustomerImpactReview'],
    forbiddenOutputTypes: ['ExternalMessage', 'A2ADispatch'],
    skillRefs: ['zoom-out', 'customer-value-review'],
    riskLevel: 'medium',
    requiresHumanConfirmation: false,
    permissionBoundaryId: 'agent-boundary-bezos',
    status: 'active',
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
]

function boundaryFor(profile: AgentProfile): AgentPermissionBoundary {
  const isClaudeCeo = profile.id === 'claude_ceo'
  const isKelvin = profile.id === 'kelvin'
  return {
    id: profile.permissionBoundaryId,
    boundaryVersion: 'sprint-10.0',
    agentId: profile.id,
    allowedActions: profile.allowedActions,
    forbiddenActions: profile.forbiddenActions,
    allowedOutputTypes: profile.allowedOutputTypes,
    forbiddenOutputTypes: profile.forbiddenOutputTypes,
    mayCreateLocalRecord: !isKelvin,
    mayCreateToolCallProposal: isClaudeCeo,
    mayRequestEval: isClaudeCeo || profile.id === 'turing',
    mayRequestKelvinReview: isClaudeCeo || profile.riskLevel === 'high',
    mayApproveLocalRecord: isKelvin,
    mayMutateTaskStatus: false,
    mayStartAgentRun: false,
    mayExecuteTool: false,
    mayCreateExecutableToolRun: false,
    mayCallExternalApi: false,
    mayCallMcp: false,
    mayWriteFile: false,
    mayUseShell: false,
    mayUseGit: false,
    mayCreatePr: false,
    mayDeploy: false,
    mayDelete: false,
    mayDispatchA2A: false,
    mayResumeExecution: false,
    mayBypassPermission: false,
    requiresHumanConfirmation: profile.requiresHumanConfirmation,
    requiresEvalForHighRisk: true,
    riskLevel: profile.riskLevel,
    securityPolicyId: defaultSecurityPolicy.id,
    commandPolicyId: defaultSecurityPolicy.commandPolicyId,
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  }
}

export const agentPermissionBoundaries = agentProfiles.map(boundaryFor)

export const skillIOContracts: SkillIOContract[] = [
  {
    id: 'skill-io-ceo-planning',
    contractVersion: 'sprint-10.0',
    skillRef: 'ai-builder-methodology',
    displayName: 'CEO Planning Contract',
    description: 'Plan, route, coordinate, and risk assess without execution.',
    skillCategory: 'planning',
    ownerAgentIds: ['claude_ceo'],
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object' },
    allowedSideEffects: 'none',
    forbiddenSideEffects: forbiddenExecutionActions,
    outputMustBeStructured: true,
    auditFieldsRequired: ['correlationId', 'actorType', 'resourceType', 'resourceId'],
    correlationRequired: true,
    redactionRequired: true,
    evalRequired: true,
    humanConfirmationRequired: true,
    forbiddenOutputs: ['ToolExecution', 'ShellCommand', 'FilePatch', 'GitOperation', 'DeployRun'],
    maxInputSizeChars: 12000,
    maxOutputSizeChars: 12000,
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
  {
    id: 'skill-io-tooling-proposal',
    contractVersion: 'sprint-10.0',
    skillRef: 'tool-call-proposal',
    displayName: 'Tooling Proposal Contract',
    description: 'Tooling means ToolCall proposal and permission reasoning only.',
    skillCategory: 'tooling',
    ownerAgentIds: ['claude_ceo', 'linus'],
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object' },
    allowedSideEffects: 'none',
    forbiddenSideEffects: forbiddenExecutionActions,
    outputMustBeStructured: true,
    auditFieldsRequired: ['correlationId', 'toolCallId', 'policyRef'],
    correlationRequired: true,
    redactionRequired: true,
    evalRequired: true,
    humanConfirmationRequired: true,
    forbiddenOutputs: ['ToolDefinition', 'ToolExecutor', 'ToolRunExecution'],
    maxInputSizeChars: 12000,
    maxOutputSizeChars: 12000,
    createdAt: sprint10CreatedAt,
    updatedAt: sprint10CreatedAt,
  },
]

export const apiAuthBoundary: ApiAuthBoundary = {
  id: 'api-auth-boundary-sprint-10',
  boundaryVersion: 'sprint-10.0',
  authMode: 'local_single_user',
  userIdRequired: false,
  roleRequired: true,
  defaultRole: 'viewer',
  agentRecordActorRole: 'agent_record',
  mutationRequiresAudit: true,
  highRiskMutationRequiresConfirmation: true,
  blockedPayloadsRejected: true,
  roles: [
    {
      id: 'owner',
      description: 'Kelvin or authenticated human owner. Can approve high-risk local records only.',
      allowedApiGroups: ['*'],
      allowedMutationTypes: ['local_record_review'],
      forbiddenMutationTypes: forbiddenExecutionActions,
      mayApproveHighRiskLocalRecord: true,
    },
    {
      id: 'operator',
      description: 'Can create local records and submit reviews. Cannot approve high-risk records.',
      allowedApiGroups: ['read', 'local_record'],
      allowedMutationTypes: ['submit_review'],
      forbiddenMutationTypes: forbiddenExecutionActions,
      mayApproveHighRiskLocalRecord: false,
    },
    {
      id: 'viewer',
      description: 'Read-only production safety views.',
      allowedApiGroups: ['read'],
      allowedMutationTypes: [],
      forbiddenMutationTypes: ['*'],
      mayApproveHighRiskLocalRecord: false,
    },
    {
      id: 'agent_record',
      description: 'Non-human local record attribution. Does not grant permission.',
      allowedApiGroups: ['local_record'],
      allowedMutationTypes: ['propose_record'],
      forbiddenMutationTypes: forbiddenExecutionActions,
      mayApproveHighRiskLocalRecord: false,
    },
  ],
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}

export const secretRedactionPolicy: SecretRedactionPolicy = {
  id: 'secret-redaction-policy-sprint-10',
  redactionVersion: 'sprint-10.0',
  status: 'active',
  secretClasses: [
    'api_key',
    'access_token',
    'refresh_token',
    'password',
    'private_key',
    'cookie',
    'session_token',
    'env_dump',
    'raw_file_content',
    'raw_shell_output',
    'raw_external_payload',
    'personal_data',
  ],
  blockedFields: ['rawPayload', 'fullFileContent', 'fullCommandOutput', 'externalPayload'],
  blockedPatterns: ['api[_-]?key', 'access[_-]?token', 'private[_-]?key', 'cookie'],
  blockedPayloadDestinations: [
    'audit_event_payload',
    'observability_event_payload',
    'recovery_point_snapshot',
    'run_journal_entry',
    'resume_token_context',
    'eval_evidence',
    'agent_prompt',
    'tool_call_policy_snapshot',
    'collaboration_plan_snapshot',
    'memory_candidate',
    'knowledge_item',
  ],
  maxAllowedExcerptChars: 1000,
  allowHashes: true,
  allowCounts: true,
  allowSummaries: true,
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}

export const productionObservabilityPolicy: ProductionObservabilityPolicy = {
  id: 'production-observability-policy-sprint-10',
  policyVersion: 'sprint-10.0',
  status: 'active',
  correlationRequired: true,
  auditRequiredForMutations: true,
  observabilityRequiredForHighRiskEvents: true,
  redactionRequired: true,
  requiredCorrelationSurfaces: [
    'chat_message',
    'route_decision',
    'harmony_task',
    'agent_run',
    'agent_result',
    'memory_entry',
    'knowledge_item',
    'context_packet',
    'a2a_message',
    'tool_call',
    'tool_permission',
    'eval_target',
    'eval_run',
    'collaboration_session',
    'release_readiness_checklist',
    'regression_gate',
  ],
  requiredAuditFields: ['eventType', 'actorType', 'resourceType', 'resourceId', 'reason'],
  requiredObservabilityFields: ['correlationId', 'resourceType', 'resourceId', 'eventType', 'message'],
  forbiddenPayloadClasses: secretRedactionPolicy.secretClasses,
  retentionPolicy: {
    auditEvents: 'append_only',
    observabilityEvents: 'append_only',
    runJournals: 'append_only',
    recoveryPoints: 'view_only',
    resumeTokens: 'view_only',
  },
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}

export const regressionGate: RegressionGate = {
  id: 'regression-gate-sprint-10',
  gateVersion: 'sprint-10.0',
  correlationId: 'corr_sprint_10_regression_gate',
  targetSprint: 'sprint_10',
  status: 'passed',
  requiredChecks: [
    ['sprint_1', 'ChatHub SSE remains available'],
    ['sprint_2', 'Router returns structured RouteDecision'],
    ['sprint_3', 'Harmony Task Engine state machine remains valid'],
    ['sprint_4', 'Agent Runtime remains analysis-only'],
    ['sprint_5', 'Memory / Knowledge / local A2A records do not auto-execute'],
    ['sprint_6', 'ToolCall proposal / Permission remains record-only'],
    ['sprint_7', 'Eval remains recommendation-only'],
    ['sprint_8', 'Observability / Recovery / Resume remains view-only'],
    ['sprint_9', 'Collaboration / A2A Runtime remains local controlled records'],
    ['sprint_10', 'Production hardening remains non-executing'],
  ].map(([sprint, name]) => ({
    id: `regression-${sprint}`,
    sprint: sprint as RegressionGate['requiredChecks'][number]['sprint'],
    name,
    expectedBehavior: name,
    status: 'passed',
    evidenceRefs: ['static-config', 'test-suite'],
    checkedAt: sprint10CreatedAt,
  })),
  forbiddenRegressions: [
    'real_tool_execution',
    'agent_execution_from_readiness',
    'auto_memory_approval',
    'a2a_dispatch',
    'resume_execution',
    'deployment_from_readiness',
  ],
  coverageSummary: {
    sprint1: true,
    sprint2: true,
    sprint3: true,
    sprint4: true,
    sprint5: true,
    sprint6: true,
    sprint7: true,
    sprint8: true,
    sprint9: true,
  },
  evidenceRefs: ['npm run test', 'npm run lint', 'npm run build'],
  reviewedBy: 'system',
  reviewedAt: sprint10CreatedAt,
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}

export const releaseReadinessChecklist: ReleaseReadinessChecklist = {
  id: 'release-readiness-sprint-10',
  checklistVersion: 'sprint-10.0',
  targetSprint: 'sprint_10',
  targetRelease: 'sprint-10-production-hardening',
  correlationId: 'corr_sprint_10_release_readiness',
  status: 'ready_for_review',
  securityPolicyId: defaultSecurityPolicy.id,
  regressionGateId: regressionGate.id,
  apiAuthBoundaryId: apiAuthBoundary.id,
  productionObservabilityPolicyId: productionObservabilityPolicy.id,
  checks: [
    ['security', 'SecurityPolicy default-deny'],
    ['auth', 'ApiAuthBoundary roles defined'],
    ['redaction', 'Blocked payload destinations protected'],
    ['audit', 'Mutations require audit records'],
    ['observability', 'Correlation surfaces defined'],
    ['regression', 'Sprint 1-9 RegressionGate coverage'],
    ['ui', 'Forbidden execution labels absent from Sprint 10 UI'],
    ['docs', 'Sprint 10 specs reviewed'],
  ].map(([category, name]) => ({
    id: `readiness-${String(category).replaceAll('_', '-')}`,
    category: category as ReleaseReadinessChecklist['checks'][number]['category'],
    name,
    description: name,
    status: 'passed',
    required: true,
    evidenceRefs: ['static-config'],
    checkedAt: sprint10CreatedAt,
  })),
  reviewedBy: 'system',
  reviewedAt: sprint10CreatedAt,
  createdAt: sprint10CreatedAt,
  updatedAt: sprint10CreatedAt,
}
